[manager]
ratio          = [ 2, 2, 4 ]
sort_by        = "natural"
sort_sensitive = true
sort_reverse 	 = false
sort_dir_first = true
sort_translit  = false
linemode       = "none"
show_hidden    = true
show_symlink   = true
scrolloff      = 5
title_format   = "Yazi: {cwd}"


[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
image_quality   = 90
sixel_fraction  = 10
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]


[opener]
editor = [
	{ run = '${EDITOR:-vim} "${@}"', desc = "Edit file in $EDITOR", block = true, for = "linux" },
]
extractor = [
	{ run = 'vim "${@}"', desc = "Open archive in vim", block = true, for = "linux" },
]
player = [
	{ run = 'mpv --force-window "${@}"', desc = "Play audio or video in mpv", orphan = true, for = "linux" },
]
match = [
	{ run = 'xdg-open "${@}"', desc = "Open file in the user's preferred application", orphan = true, for = "linux" },
]


[open]
rules = [
	{ mime = "text/*", use = [ "editor", "match" ] },
	{ mime = "application/{json,x-ndjson}", use = [ "editor", "match" ] },
	{ mime = "image/*", use = [ "match" ] },
	{ mime = "{audio,video}/*", use = [ "play", "match" ] },
	{ mime = "application/{,g}zip", use = [ "extractor", "match" ] },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extractor", "match" ] },
	{ name = "*", use = [ "match" ] },
]


[log]
enable = false